# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-29 05:26
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CRRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(default=datetime.datetime(2017, 11, 29, 5, 26, 18, 588622))),
                ('bond_code', models.CharField(max_length=20)),
                ('base_year', models.CharField(max_length=10)),
                ('intermediate_data_file', models.CharField(max_length=50)),
                ('internal_score_debt', models.FloatField()),
                ('internal_rating_debt', models.CharField(max_length=5)),
                ('internal_score_company', models.FloatField()),
                ('internal_rating_company', models.CharField(max_length=5)),
                ('external_rating_debt', models.CharField(max_length=5, null=True)),
                ('external_rating_company', models.CharField(max_length=5, null=True)),
                ('background', models.IntegerField()),
                ('background_remarks', models.CharField(max_length=50, null=True)),
                ('industry', models.IntegerField()),
                ('industry_remarks', models.CharField(max_length=50, null=True)),
                ('external_warranty', models.IntegerField()),
                ('external_warranty_remarks', models.CharField(max_length=50, null=True)),
                ('asset_warranty', models.IntegerField()),
                ('asset_warranty_remarks', models.CharField(max_length=50, null=True)),
                ('industry_boom', models.IntegerField()),
                ('industry_boom_remarks', models.CharField(max_length=50, null=True)),
                ('industry_prospects', models.IntegerField()),
                ('industry_prospects_remarks', models.CharField(max_length=50, null=True)),
                ('industry_rank', models.IntegerField()),
                ('industry_rank_remarks', models.CharField(max_length=50, null=True)),
                ('fund_usage', models.IntegerField()),
                ('fund_usage_remarks', models.CharField(max_length=50, null=True)),
                ('future_expenditure', models.IntegerField()),
                ('future_expenditure_remarks', models.CharField(max_length=50, null=True)),
                ('pct_major_shareholders', models.FloatField()),
                ('pct_profit_of_parent', models.FloatField()),
                ('total_asset', models.FloatField()),
                ('net_asset', models.FloatField()),
                ('net_asset_chg', models.FloatField()),
                ('revenue', models.FloatField()),
                ('net_profit', models.FloatField()),
                ('operating_profit', models.FloatField()),
                ('EBITDA', models.FloatField()),
                ('operating_cashflow', models.FloatField()),
                ('gross_margin', models.FloatField()),
                ('profit_margin', models.FloatField()),
                ('gross_margin_std', models.FloatField()),
                ('gross_margin_chg', models.FloatField()),
                ('roe', models.FloatField()),
                ('short_solvency_1', models.FloatField()),
                ('short_solvency_2', models.FloatField()),
                ('debt_ratio_with_interest', models.FloatField()),
                ('debt_ratio_with_interest_chg', models.FloatField()),
                ('debt_ratio', models.FloatField()),
                ('cost_ratio', models.FloatField()),
                ('fixed_asset_ratio', models.FloatField()),
                ('operating_cf_to_debt', models.FloatField()),
                ('operating_cf_std', models.FloatField()),
                ('ebitda_to_debt', models.FloatField()),
                ('fixed_asset_turnover', models.FloatField()),
                ('inventory_turnover_days', models.FloatField()),
                ('receivable_turnover_days', models.FloatField()),
                ('rest_credit_to_debt', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='CRResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(default=datetime.datetime(2017, 11, 29, 5, 26, 18, 593450))),
                ('bond_code', models.CharField(max_length=20)),
                ('base_year', models.CharField(max_length=10)),
                ('internal_score_debt', models.FloatField()),
                ('internal_rating_debt', models.CharField(max_length=5)),
                ('internal_score_company', models.FloatField()),
                ('internal_rating_company', models.CharField(max_length=5)),
                ('external_rating_debt', models.CharField(max_length=5, null=True)),
                ('external_rating_company', models.CharField(max_length=5, null=True)),
                ('record', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='record_id', to='account.CRRecord')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='crresult',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='crrecord',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
