# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-06 10:13
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='crrecord',
            name='bond_name',
            field=models.CharField(default='bond_name', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='crrecord',
            name='bond_type',
            field=models.CharField(default='bond_type', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='crrecord',
            name='company_name',
            field=models.CharField(default='company_name', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='crresult',
            name='bond_name',
            field=models.CharField(default='bond_name', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='crresult',
            name='bond_type',
            field=models.CharField(default='bond_type', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='crresult',
            name='company_name',
            field=models.CharField(default='company_name', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='crrecord',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 6, 10, 12, 43, 692711)),
        ),
        migrations.AlterField(
            model_name='crresult',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 6, 10, 12, 43, 693711)),
        ),
    ]
