# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-14 08:40
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20171214_0834'),
    ]

    operations = [
        migrations.AddField(
            model_name='crresult',
            name='intermediate_data_file',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='crrecord',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 14, 8, 39, 47, 733413)),
        ),
        migrations.AlterField(
            model_name='crrecord_bond1',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 14, 8, 39, 47, 736413)),
        ),
        migrations.AlterField(
            model_name='crrecord_bond2',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 14, 8, 39, 47, 738408)),
        ),
        migrations.AlterField(
            model_name='crrecord_bond3',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 14, 8, 39, 47, 739408)),
        ),
        migrations.AlterField(
            model_name='crresult',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 14, 8, 39, 47, 741409)),
        ),
    ]
