# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-14 09:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20171214_0840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crrecord',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 14, 9, 33, 54, 982768)),
        ),
        migrations.AlterField(
            model_name='crrecord_bond1',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 14, 9, 33, 54, 983767)),
        ),
        migrations.AlterField(
            model_name='crrecord_bond2',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 14, 9, 33, 54, 985767)),
        ),
        migrations.AlterField(
            model_name='crrecord_bond3',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 14, 9, 33, 54, 986768)),
        ),
        migrations.AlterField(
            model_name='crresult',
            name='bond_type',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='crresult',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 14, 9, 33, 54, 988767)),
        ),
    ]
